-- =====================================================
-- MIGRATION 004: Order Management Tables
-- =====================================================
-- Purpose: Complete order processing system with discounts
-- Tables: orders, order_items, discounts
-- Dependencies: profiles, addresses (from 001, 003), variants (from 002)
-- =====================================================

-- =====================================================
-- SECTION 1: Orders Table
-- =====================================================
-- Purpose: Customer purchase records
-- Relationship: Many-to-one with profiles, many-to-one with addresses
-- RLS: Enabled (users view own orders, admins view/update all)

CREATE TABLE orders (
  -- Primary key
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- User relationship
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE RESTRICT,

  -- Unique order identifier
  order_number TEXT NOT NULL UNIQUE,

  -- Order status workflow
  status TEXT NOT NULL DEFAULT 'pending' CHECK (
    status IN ('pending', 'paid', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded')
  ),

  -- Pricing breakdown (all in USD)
  subtotal DECIMAL(10,2) NOT NULL CHECK (subtotal >= 0),
  discount_amount DECIMAL(10,2) DEFAULT 0 CHECK (discount_amount >= 0),
  tax_amount DECIMAL(10,2) DEFAULT 0 CHECK (tax_amount >= 0),
  shipping_amount DECIMAL(10,2) DEFAULT 0 CHECK (shipping_amount >= 0),
  total DECIMAL(10,2) NOT NULL CHECK (total >= 0),

  -- Shipping information
  shipping_address_id UUID REFERENCES addresses(id) ON DELETE SET NULL,

  -- Payment information
  payment_status TEXT NOT NULL DEFAULT 'unpaid' CHECK (
    payment_status IN ('unpaid', 'paid', 'refunded', 'failed')
  ),
  payment_method TEXT,
  payment_intent_id TEXT, -- Stripe PaymentIntent ID

  -- Additional information
  notes TEXT,

  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX idx_orders_user_id ON orders(user_id);
CREATE INDEX idx_orders_order_number ON orders(order_number);
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_orders_payment_status ON orders(payment_status);
CREATE INDEX idx_orders_created_at ON orders(created_at DESC);

-- Enable Row Level Security
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- Auto-update timestamp trigger
CREATE TRIGGER update_orders_updated_at
  BEFORE UPDATE ON orders
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Add comments for documentation
COMMENT ON TABLE orders IS 'Customer purchase records. Order workflow: pending → paid → processing → shipped → delivered';
COMMENT ON COLUMN orders.order_number IS 'Unique order identifier (format: YYYYMM00001). Generated by generate_order_number() function.';
COMMENT ON COLUMN orders.status IS 'Order fulfillment status: pending, paid, processing, shipped, delivered, cancelled, refunded';
COMMENT ON COLUMN orders.payment_status IS 'Payment tracking: unpaid, paid, refunded, failed';
COMMENT ON COLUMN orders.payment_intent_id IS 'Stripe PaymentIntent ID for reconciliation';
COMMENT ON COLUMN orders.total IS 'Final amount: subtotal - discount_amount + tax_amount + shipping_amount';

-- =====================================================
-- SECTION 2: Order Items Table
-- =====================================================
-- Purpose: Order line items with snapshot pattern
-- Relationship: Many-to-one with orders, many-to-one with variants
-- RLS: Enabled (users view own order items, admins view all)

CREATE TABLE order_items (
  -- Primary key
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- Order relationship
  order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,

  -- Variant relationship (historical reference)
  variant_id UUID NOT NULL REFERENCES variants(id) ON DELETE RESTRICT,

  -- SNAPSHOT PATTERN: Store product/variant details at time of purchase
  -- This protects against future price/name changes
  product_name TEXT NOT NULL,
  variant_name TEXT NOT NULL,
  sku TEXT NOT NULL,

  -- Quantity and pricing
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  unit_price DECIMAL(10,2) NOT NULL CHECK (unit_price >= 0),
  total_price DECIMAL(10,2) NOT NULL CHECK (total_price >= 0),

  -- Timestamp (no updated_at - immutable after creation)
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX idx_order_items_order_id ON order_items(order_id);
CREATE INDEX idx_order_items_variant_id ON order_items(variant_id);

-- Enable Row Level Security
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;

-- Add comments for documentation
COMMENT ON TABLE order_items IS 'Order line items using snapshot pattern. Product/variant details frozen at purchase time for historical accuracy.';
COMMENT ON COLUMN order_items.product_name IS 'Snapshot of product name at time of purchase';
COMMENT ON COLUMN order_items.variant_name IS 'Snapshot of variant name at time of purchase';
COMMENT ON COLUMN order_items.sku IS 'Snapshot of SKU at time of purchase';
COMMENT ON COLUMN order_items.unit_price IS 'Price per item at time of purchase (product.base_price + variant.price_adjustment)';
COMMENT ON COLUMN order_items.total_price IS 'unit_price * quantity';

-- =====================================================
-- SECTION 3: Discounts Table
-- =====================================================
-- Purpose: Coupon codes and promotional discounts
-- Relationship: None (standalone)
-- RLS: Enabled (public read for active discounts, admins manage)

CREATE TABLE discounts (
  -- Primary key
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- Discount code
  code TEXT NOT NULL UNIQUE,

  -- Discount type and value
  type TEXT NOT NULL CHECK (type IN ('percentage', 'fixed')),
  value DECIMAL(10,2) NOT NULL CHECK (value > 0),

  -- Conditions
  min_purchase_amount DECIMAL(10,2) DEFAULT 0,

  -- Usage tracking
  max_uses INTEGER,
  times_used INTEGER DEFAULT 0 CHECK (times_used >= 0),

  -- Status
  is_active BOOLEAN DEFAULT TRUE,

  -- Validity period
  starts_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,

  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Constraint: Usage can't exceed max_uses
  CONSTRAINT check_max_uses CHECK (max_uses IS NULL OR times_used <= max_uses)
);

-- Indexes for performance
CREATE INDEX idx_discounts_code ON discounts(code);
CREATE INDEX idx_discounts_is_active ON discounts(is_active);

-- Enable Row Level Security
ALTER TABLE discounts ENABLE ROW LEVEL SECURITY;

-- Auto-update timestamp trigger
CREATE TRIGGER update_discounts_updated_at
  BEFORE UPDATE ON discounts
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Add comments for documentation
COMMENT ON TABLE discounts IS 'Coupon codes and promotional discounts. Supports percentage and fixed amount discounts.';
COMMENT ON COLUMN discounts.type IS 'Discount type: percentage (e.g., 10% off) or fixed (e.g., $5 off)';
COMMENT ON COLUMN discounts.value IS 'Discount value. For percentage: 10 = 10%. For fixed: 5 = $5 off.';
COMMENT ON COLUMN discounts.min_purchase_amount IS 'Minimum cart value required to use discount';
COMMENT ON COLUMN discounts.max_uses IS 'Maximum number of times code can be used. NULL = unlimited.';
COMMENT ON COLUMN discounts.times_used IS 'Current usage count. Incremented on each order.';

-- =====================================================
-- END OF MIGRATION 004
-- =====================================================
